/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as CheatsheetsRouteImport } from './routes/cheatsheets'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIdRouteImport } from './routes/projects_.$id'
import { Route as LessonIdRouteImport } from './routes/lesson.$id'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const CheatsheetsRoute = CheatsheetsRouteImport.update({
  id: '/cheatsheets',
  path: '/cheatsheets',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects_/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonIdRoute = LessonIdRouteImport.update({
  id: '/lesson/$id',
  path: '/lesson/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cheatsheets': typeof CheatsheetsRoute
  '/examples': typeof ExamplesRoute
  '/glossary': typeof GlossaryRoute
  '/interview': typeof InterviewRoute
  '/modules': typeof ModulesRoute
  '/playground': typeof PlaygroundRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/lesson/$id': typeof LessonIdRoute
  '/projects/$id': typeof ProjectsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cheatsheets': typeof CheatsheetsRoute
  '/examples': typeof ExamplesRoute
  '/glossary': typeof GlossaryRoute
  '/interview': typeof InterviewRoute
  '/modules': typeof ModulesRoute
  '/playground': typeof PlaygroundRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/lesson/$id': typeof LessonIdRoute
  '/projects/$id': typeof ProjectsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cheatsheets': typeof CheatsheetsRoute
  '/examples': typeof ExamplesRoute
  '/glossary': typeof GlossaryRoute
  '/interview': typeof InterviewRoute
  '/modules': typeof ModulesRoute
  '/playground': typeof PlaygroundRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/lesson/$id': typeof LessonIdRoute
  '/projects_/$id': typeof ProjectsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cheatsheets'
    | '/examples'
    | '/glossary'
    | '/interview'
    | '/modules'
    | '/playground'
    | '/profile'
    | '/projects'
    | '/lesson/$id'
    | '/projects/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cheatsheets'
    | '/examples'
    | '/glossary'
    | '/interview'
    | '/modules'
    | '/playground'
    | '/profile'
    | '/projects'
    | '/lesson/$id'
    | '/projects/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/cheatsheets'
    | '/examples'
    | '/glossary'
    | '/interview'
    | '/modules'
    | '/playground'
    | '/profile'
    | '/projects'
    | '/lesson/$id'
    | '/projects_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CheatsheetsRoute: typeof CheatsheetsRoute
  ExamplesRoute: typeof ExamplesRoute
  GlossaryRoute: typeof GlossaryRoute
  InterviewRoute: typeof InterviewRoute
  ModulesRoute: typeof ModulesRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
  LessonIdRoute: typeof LessonIdRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cheatsheets': {
      id: '/cheatsheets'
      path: '/cheatsheets'
      fullPath: '/cheatsheets'
      preLoaderRoute: typeof CheatsheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$id': {
      id: '/projects_/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$id': {
      id: '/lesson/$id'
      path: '/lesson/$id'
      fullPath: '/lesson/$id'
      preLoaderRoute: typeof LessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CheatsheetsRoute: CheatsheetsRoute,
  ExamplesRoute: ExamplesRoute,
  GlossaryRoute: GlossaryRoute,
  InterviewRoute: InterviewRoute,
  ModulesRoute: ModulesRoute,
  PlaygroundRoute: PlaygroundRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRoute,
  LessonIdRoute: LessonIdRoute,
  ProjectsIdRoute: ProjectsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
