/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LessonIdRouteImport } from './routes/lesson.$id'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonIdRoute = LessonIdRouteImport.update({
  id: '/lesson/$id',
  path: '/lesson/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/modules': typeof ModulesRoute
  '/playground': typeof PlaygroundRoute
  '/profile': typeof ProfileRoute
  '/lesson/$id': typeof LessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/modules': typeof ModulesRoute
  '/playground': typeof PlaygroundRoute
  '/profile': typeof ProfileRoute
  '/lesson/$id': typeof LessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/modules': typeof ModulesRoute
  '/playground': typeof PlaygroundRoute
  '/profile': typeof ProfileRoute
  '/lesson/$id': typeof LessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/modules' | '/playground' | '/profile' | '/lesson/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/modules' | '/playground' | '/profile' | '/lesson/$id'
  id: '__root__' | '/' | '/modules' | '/playground' | '/profile' | '/lesson/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModulesRoute: typeof ModulesRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ProfileRoute: typeof ProfileRoute
  LessonIdRoute: typeof LessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$id': {
      id: '/lesson/$id'
      path: '/lesson/$id'
      fullPath: '/lesson/$id'
      preLoaderRoute: typeof LessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModulesRoute: ModulesRoute,
  PlaygroundRoute: PlaygroundRoute,
  ProfileRoute: ProfileRoute,
  LessonIdRoute: LessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
